apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: aWrongjob
  namespace: default
spec:
  schedule: "1 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: aWrongjob
              image: "123edw"
              args:
                - /usr/bin/php
                - /www/demo.php
          imagePullSecrets:
            - name: secret
          restartPolicy: OnFailure