apiVersion: v1
kind: Service
metadata:
  name: kube-node
  namespace: default
  labels:
    component: apiserver
spec:
  type: ClusterIP
  selector:
    k8s-app: test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
