apiVersion: v1
kind: Service
metadata:
  name: kube-node
  namespace: ingress-nginx
  labels:
    app: webtest
spec:
  type: ClusterIP
  selector:
    k8s-app: test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
